/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.11 and Signal Processing Toolbox 8.7.
 * Generated on: 06-May-2023 23:09:12
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 61
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 */

// Here are the highpass filters: 5/6/23.
// All designed with stopband of less than 80 db. 
// Transition bands: 1000Hz each
// Example: if cutoff = 5kHz, then the stopband is at 4kHz
// we have 8 options atm

#include <stdint.h>
const int HIPASS_LENGTH = 61;

 uint8_t HIPASS_CUT_1000[61] = {
      0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
      0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
      0,    0,    0,    0,    0,    0,  123,    0,    0,    0,    0,    0,
      0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
      0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
      0
};

const uint8_t HIPASS_CUT_1100[61] = {
      0,    0,    0,    0,    0,    0,    1,    1,    1,    1,    1,    1,
      1,    1,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
      0,    0,    0,    0,    0,    0,  119,    0,    0,    0,    0,    0,
      0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    1,
      1,    1,    1,    1,    1,    1,    1,    0,    0,    0,    0,    0,
      0
};

const uint8_t HIPASS_CUT_1250[61] = {
      0,    0,    0,    0,    0,    0,    0,    0,    0,    1,    1,    1,
      1,    1,    1,    1,    1,    0,    0,    0,    0,    0,    0,    0,
      0,    0,    0,    0,    0,    0,  118,    0,    0,    0,    0,    0,
      0,    0,    0,    0,    0,    0,    0,    0,    1,    1,    1,    1,
      1,    1,    1,    1,    0,    0,    0,    0,    0,    0,    0,    0,
      0
};

const uint8_t HIPASS_CUT_1500[61] = {
      0,    1,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
      0,    1,    1,    2,    2,    2,    2,    2,    1,    0,    0,    0,
      0,    0,    0,    0,    0,    0,  114,    0,    0,    0,    0,    0,
      0,    0,    0,    0,    1,    2,    2,    2,    2,    2,    1,    1,
      0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    1,
      0
};

const uint8_t HIGHPASS_CUT_2000[61] = {
      1,    0,    0,    0,    0,    0,    1,    1,    1,    1,    0,    0,
      0,    0,    0,    0,    0,    0,    1,    3,    3,    4,    3,    1,
      0,    0,    0,    0,    0,    0,  108,    0,    0,    0,    0,    0,
      0,    1,    3,    4,    3,    3,    1,    0,    0,    0,    0,    0,
      0,    0,    0,    1,    1,    1,    1,    0,    0,    0,    0,    0,
      1
};

const uint8_t HIPASS_CUT_3000[61] = {
      0,    2,    0,    0,    0,    0,    0,    1,    1,    0,    0,    0,
      0,    0,    0,    2,    2,    1,    0,    0,    0,    0,    1,    4,
      6,    5,    0,    0,    0,    0,   97,    0,    0,    0,    0,    5,
      6,    4,    1,    0,    0,    0,    0,    1,    2,    2,    0,    0,
      0,    0,    0,    0,    1,    1,    0,    0,    0,    0,    0,    2,
      0
};

const uint8_t HIPASS_CUT_4000[61] = {
      0,    0,    1,    1,    0,    0,    0,    1,    1,    0,    0,    0,
      0,    1,    2,    0,    0,    0,    0,    3,    3,    0,    0,    0,
      0,    7,    9,    0,    0,    0,   85,    0,    0,    0,    9,    7,
      0,    0,    0,    0,    3,    3,    0,    0,    0,    0,    2,    1,
      0,    0,    0,    0,    1,    1,    0,    0,    0,    1,    1,    0,
      0
};

const uint8_t HIGHPASS_CUT_5000[61] = {
      0,    1,    0,    1,    1,    0,    0,    0,    1,    0,    0,    0,
      1,    1,    0,    0,    0,    2,    1,    0,    0,    2,    4,    0,
      0,    0,    8,   10,    0,    0,   73,    0,    0,   10,    8,    0,
      0,    0,    4,    2,    0,    0,    1,    2,    0,    0,    0,    1,
      1,    0,    0,    0,    1,    0,    0,    0,    1,    1,    0,    1,
      0
};

