/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.11 and Signal Processing Toolbox 8.7.
 * Generated on: 24-Apr-2023 17:34:52
 */

#include <stdint.h>
/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 110
 * Stable            : Yes
 * Linear Phase      : Yes (Type 2)
 */

/* General type conversion for MATLAB generated C-code  */
// #include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2021b\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   int32 filter coefficients.
 */
const int FIR_stop_400_len = 110;
const uint32_t FIR_stop_400[110] = {
       4121261,     1465410,     1718126,     1994394,     2295301,     2621178,
       2972235,     3348486,     3750546,     4179452,     4635551,     5117572,
       5623553,     6154450,     6713126,     7297662,     7900259,     8531763,
       9180980,     9852072,    10541867,    11249175,    11971851,    12708238,
      13457066,    14216577,    14984077,    15756817,    16533404,    17311492,
      18087810,    18859809,    19626466,    20382485,    21127846,    21858551,
      22572751,    23267101,    23939187,    24586781,    25207358,    25798211,
      26357057,    26882185,    27371008,    27821966,    28233276,    28603501,
      28930243,    29213241,    29450674,    29642152,    29786113,    29882437,
      29930763,    29930763,    29882437,    29786113,    29642152,    29450674,
      29213241,    28930243,    28603501,    28233276,    27821966,    27371008,
      26882185,    26357057,    25798211,    25207358,    24586781,    23939187,
      23267101,    22572751,    21858551,    21127846,    20382485,    19626466,
      18859809,    18087810,    17311492,    16533404,    15756817,    14984077,
      14216577,    13457066,    12708238,    11971851,    11249175,    10541867,
       9852072,     9180980,     8531763,     7900259,     7297662,     6713126,
       6154450,     5623553,     5117572,     4635551,     4179452,     3750546,
       3348486,     2972235,     2621178,     2295301,     1994394,     1718126,
       1465410,     4121261
};
